// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.demoScripts;

import com.rational.test.ft.script.RationalTestScript;
/**
 * Script Name   : <b>ObjectMapDemo</b><br>
 * Generated     : <b>2010/05/29 9:22:47 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  May 29, 2010
 * @author Administrator
 */
public abstract class ObjectMapDemoHelper extends RationalTestScript
{
	

	protected ObjectMapDemoHelper()
	{
		setScriptName("demoScripts.ObjectMapDemo");
	}
	
}

