// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.demoScripts;

import com.rational.test.ft.script.RationalTestScript;
/**
 * Script Name   : <b>PlaybackMonitorDemo</b><br>
 * Generated     : <b>2010/05/30 10:09:09 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  May 30, 2010
 * @author mlfreeman
 */
public abstract class PlaybackMonitorDemoHelper extends RationalTestScript
{
	

	protected PlaybackMonitorDemoHelper()
	{
		setScriptName("demoScripts.PlaybackMonitorDemo");
	}
	
}

