//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.28 at 12:49:50 PM EDT
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jazz.net/xmlns/alm/qm/qmadapter/task/v0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ibm.rqm.xml.bind.tasks;

