// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions. Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.demoScripts.innovate2011.amazon.wishlist;

import com.rational.test.ft.script.RationalTestScript;

/**
 * Script Name : <b>DeleteItem</b><br>
 * Generated : <b>2011/06/07 11:56:30 AM</b><br>
 * Description : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since June 07, 2011
 * @author laguilar
 */
public abstract class DeleteItemHelper extends RationalTestScript
{
    
    protected DeleteItemHelper()
    {
        setScriptName("demoScripts.innovate2011.amazon.wishlist.DeleteItem");
    }
    
}
