// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.demoScripts.innovate2012;

import com.advancedrft.common.lang.Reflection;
import com.rational.test.ft.script.RationalTestScript;
/**
 * Script Name   : <b>JythonLauncher</b><br>
 * Generated     : <b>2012/05/15 6:44:56 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  May 15, 2012
 * @author vmuser
 */
public abstract class JythonLauncherHelper extends RationalTestScript
{
	

	protected JythonLauncherHelper()
	{
		setScriptName("demoScripts.innovate2012.JythonLauncher");
		Reflection.foreignClassLoaders.add(getClass().getClassLoader());
	}
	
}

