// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.demoScripts.googleDemo;

import com.rational.test.ft.script.RationalTestScript;
/**
 * Script Name   : <b>FinanceDemo</b><br>
 * Generated     : <b>2010/05/31 8:49:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  May 31, 2010
 * @author Administrator
 */
public abstract class FinanceDemoHelper extends RationalTestScript
{
	

	protected FinanceDemoHelper()
	{
		setScriptName("demoScripts.googleDemo.FinanceDemo");
	}
	
}

