//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.28 at 12:49:50 PM EDT
//

package org.w3._2005.atom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import com.ibm.rqm.xml.bind.Adaptertask;
import com.ibm.rqm.xml.bind.Attachment;
import com.ibm.rqm.xml.bind.Builddefinition;
import com.ibm.rqm.xml.bind.Buildrecord;
import com.ibm.rqm.xml.bind.Category;
import com.ibm.rqm.xml.bind.CategoryType;
import com.ibm.rqm.xml.bind.Configuration;
import com.ibm.rqm.xml.bind.Contributor;
import com.ibm.rqm.xml.bind.Datapool;
import com.ibm.rqm.xml.bind.Executionresult;
import com.ibm.rqm.xml.bind.Executionworkitem;
import com.ibm.rqm.xml.bind.Job;
import com.ibm.rqm.xml.bind.Jobresult;
import com.ibm.rqm.xml.bind.Keyword;
import com.ibm.rqm.xml.bind.Labresource;
import com.ibm.rqm.xml.bind.LegacyTeamArea;
import com.ibm.rqm.xml.bind.Objective;
import com.ibm.rqm.xml.bind.Project;
import com.ibm.rqm.xml.bind.Remotescript;
import com.ibm.rqm.xml.bind.Request;
import com.ibm.rqm.xml.bind.Requirement;
import com.ibm.rqm.xml.bind.Reservation;
import com.ibm.rqm.xml.bind.Resourcecollection;
import com.ibm.rqm.xml.bind.Resourcegroup;
import com.ibm.rqm.xml.bind.Suiteexecutionrecord;
import com.ibm.rqm.xml.bind.Template;
import com.ibm.rqm.xml.bind.Testcase;
import com.ibm.rqm.xml.bind.Testcell;
import com.ibm.rqm.xml.bind.Testphase;
import com.ibm.rqm.xml.bind.Testplan;
import com.ibm.rqm.xml.bind.Testscript;
import com.ibm.rqm.xml.bind.Testsuite;
import com.ibm.rqm.xml.bind.Testsuitelog;
import com.ibm.rqm.xml.bind.Tooladapter;
import com.ibm.rqm.xml.bind.Workitem;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entry" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="link">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="title">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="summary">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;any processContents='skip' namespace='http://www.w3.org/1999/xhtml' maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="content">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}executionresult"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testplan"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testphase"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testcase"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testscript"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}executionworkitem"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}requirement"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}datapool"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}tooladapter"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}adaptertask"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}template"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testsuite"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}keyword"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testsuitelog"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}suiteexecutionrecord"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}configuration"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}remotescript"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}request"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}reservation"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}resourcecollection"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}resourcegroup"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}labresource"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}job"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}jobresult"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}teamarea"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}contributor"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}workitem"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}buildrecord"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}builddefinition"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testcell"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}objective"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}project"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}attachment"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}category"/>
 *                             &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}categoryType"/>
 *                           &lt;/choice>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"title", "id", "link", "entry"})
@XmlRootElement(name = "feed")
public class Feed
{
    
    @XmlElement(required = true)
    protected Feed.Title       title;
    
    @XmlElement(required = true)
    protected String           id;
    
    @XmlElement(required = true)
    protected List<Feed.Link>  link;
    
    @XmlElement(required = true)
    protected List<Feed.Entry> entry;
    
    /**
     * Gets the value of the title property.
     * 
     * @return possible object is {@link Feed.Title }
     */
    public Feed.Title getTitle()
    {
        return title;
    }
    
    /**
     * Sets the value of the title property.
     * 
     * @param value
     *            allowed object is {@link Feed.Title }
     */
    public void setTitle(Feed.Title value)
    {
        this.title = value;
    }
    
    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public String getId()
    {
        return id;
    }
    
    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setId(String value)
    {
        this.id = value;
    }
    
    /**
     * Gets the value of the link property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the link property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLink().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Feed.Link }
     */
    public List<Feed.Link> getLink()
    {
        if (link == null)
        {
            link = new ArrayList<Feed.Link>();
        }
        return this.link;
    }
    
    /**
     * Gets the value of the entry property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the entry property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getEntry().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Feed.Entry }
     */
    public List<Feed.Entry> getEntry()
    {
        if (entry == null)
        {
            entry = new ArrayList<Feed.Entry>();
        }
        return this.entry;
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="link">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="title">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="summary">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;any processContents='skip' namespace='http://www.w3.org/1999/xhtml' maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="content">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}executionresult"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testplan"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testphase"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testcase"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testscript"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}executionworkitem"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}requirement"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}datapool"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}tooladapter"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}adaptertask"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}template"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testsuite"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}keyword"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testsuitelog"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}suiteexecutionrecord"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}configuration"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}remotescript"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}request"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}reservation"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}resourcecollection"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}resourcegroup"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}labresource"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}job"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}jobresult"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}teamarea"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}contributor"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}workitem"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}buildrecord"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}builddefinition"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testcell"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}objective"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}project"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}attachment"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}category"/>
     *                   &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}categoryType"/>
     *                 &lt;/choice>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"id", "link", "title", "summary", "updated", "content"})
    public static class Entry
    {
        
        @XmlElement(required = true)
        protected String               id;
        
        @XmlElement(required = true)
        protected Feed.Entry.Link      link;
        
        @XmlElement(required = true)
        protected Feed.Entry.Title     title;
        
        @XmlElement(required = true)
        protected Feed.Entry.Summary   summary;
        
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar updated;
        
        @XmlElement(required = true)
        protected Feed.Entry.Content   content;
        
        /**
         * Gets the value of the id property.
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
        /**
         * Gets the value of the link property.
         * 
         * @return possible object is {@link Feed.Entry.Link }
         */
        public Feed.Entry.Link getLink()
        {
            return link;
        }
        
        /**
         * Sets the value of the link property.
         * 
         * @param value
         *            allowed object is {@link Feed.Entry.Link }
         */
        public void setLink(Feed.Entry.Link value)
        {
            this.link = value;
        }
        
        /**
         * Gets the value of the title property.
         * 
         * @return possible object is {@link Feed.Entry.Title }
         */
        public Feed.Entry.Title getTitle()
        {
            return title;
        }
        
        /**
         * Sets the value of the title property.
         * 
         * @param value
         *            allowed object is {@link Feed.Entry.Title }
         */
        public void setTitle(Feed.Entry.Title value)
        {
            this.title = value;
        }
        
        /**
         * Gets the value of the summary property.
         * 
         * @return possible object is {@link Feed.Entry.Summary }
         */
        public Feed.Entry.Summary getSummary()
        {
            return summary;
        }
        
        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *            allowed object is {@link Feed.Entry.Summary }
         */
        public void setSummary(Feed.Entry.Summary value)
        {
            this.summary = value;
        }
        
        /**
         * Gets the value of the updated property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getUpdated()
        {
            return updated;
        }
        
        /**
         * Sets the value of the updated property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         */
        public void setUpdated(XMLGregorianCalendar value)
        {
            this.updated = value;
        }
        
        /**
         * Gets the value of the content property.
         * 
         * @return possible object is {@link Feed.Entry.Content }
         */
        public Feed.Entry.Content getContent()
        {
            return content;
        }
        
        /**
         * Sets the value of the content property.
         * 
         * @param value
         *            allowed object is {@link Feed.Entry.Content }
         */
        public void setContent(Feed.Entry.Content value)
        {
            this.content = value;
        }
        
        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}executionresult"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testplan"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testphase"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testcase"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testscript"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}executionworkitem"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}requirement"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}datapool"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}tooladapter"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}adaptertask"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}template"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testsuite"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}keyword"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testsuitelog"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}suiteexecutionrecord"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}configuration"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}remotescript"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}request"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}reservation"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}resourcecollection"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}resourcegroup"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}labresource"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}job"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}jobresult"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}teamarea"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}contributor"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}workitem"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}buildrecord"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}builddefinition"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}testcell"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}objective"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}project"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}attachment"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}category"/>
         *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}categoryType"/>
         *       &lt;/choice>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"executionresult", "testplan", "testphase", "testcase", "testscript", "executionworkitem", "requirement", "datapool", "tooladapter", "adaptertask", "template", "testsuite", "keyword", "testsuitelog", "suiteexecutionrecord", "configuration", "remotescript", "request", "reservation", "resourcecollection", "resourcegroup", "labresource", "job", "jobresult", "teamarea", "contributor", "workitem", "buildrecord", "builddefinition", "testcell", "objective", "project", "attachment", "category", "categoryType"})
        public static class Content
        {
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Executionresult      executionresult;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testplan             testplan;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testphase            testphase;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testcase             testcase;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testscript           testscript;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Executionworkitem    executionworkitem;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Requirement          requirement;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Datapool             datapool;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Tooladapter          tooladapter;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Adaptertask          adaptertask;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Template             template;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testsuite            testsuite;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Keyword              keyword;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testsuitelog         testsuitelog;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Suiteexecutionrecord suiteexecutionrecord;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Configuration        configuration;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Remotescript         remotescript;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Request              request;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Reservation          reservation;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Resourcecollection   resourcecollection;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Resourcegroup        resourcegroup;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Labresource          labresource;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Job                  job;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Jobresult            jobresult;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected LegacyTeamArea       teamarea;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Contributor          contributor;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Workitem             workitem;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Buildrecord          buildrecord;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Builddefinition      builddefinition;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Testcell             testcell;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Objective            objective;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Project              project;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Attachment           attachment;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected Category             category;
            
            @XmlElement(namespace = "http://jazz.net/xmlns/alm/qm/v0.1/")
            protected CategoryType         categoryType;
            
            @XmlAttribute
            protected String               type;
            
            /**
             * Gets the value of the executionresult property.
             * 
             * @return possible object is {@link Executionresult }
             */
            public Executionresult getExecutionresult()
            {
                return executionresult;
            }
            
            /**
             * Sets the value of the executionresult property.
             * 
             * @param value
             *            allowed object is {@link Executionresult }
             */
            public void setExecutionresult(Executionresult value)
            {
                this.executionresult = value;
            }
            
            /**
             * Gets the value of the testplan property.
             * 
             * @return possible object is {@link Testplan }
             */
            public Testplan getTestplan()
            {
                return testplan;
            }
            
            /**
             * Sets the value of the testplan property.
             * 
             * @param value
             *            allowed object is {@link Testplan }
             */
            public void setTestplan(Testplan value)
            {
                this.testplan = value;
            }
            
            /**
             * Gets the value of the testphase property.
             * 
             * @return possible object is {@link Testphase }
             */
            public Testphase getTestphase()
            {
                return testphase;
            }
            
            /**
             * Sets the value of the testphase property.
             * 
             * @param value
             *            allowed object is {@link Testphase }
             */
            public void setTestphase(Testphase value)
            {
                this.testphase = value;
            }
            
            /**
             * Gets the value of the testcase property.
             * 
             * @return possible object is {@link Testcase }
             */
            public Testcase getTestcase()
            {
                return testcase;
            }
            
            /**
             * Sets the value of the testcase property.
             * 
             * @param value
             *            allowed object is {@link Testcase }
             */
            public void setTestcase(Testcase value)
            {
                this.testcase = value;
            }
            
            /**
             * Gets the value of the testscript property.
             * 
             * @return possible object is {@link Testscript }
             */
            public Testscript getTestscript()
            {
                return testscript;
            }
            
            /**
             * Sets the value of the testscript property.
             * 
             * @param value
             *            allowed object is {@link Testscript }
             */
            public void setTestscript(Testscript value)
            {
                this.testscript = value;
            }
            
            /**
             * Gets the value of the executionworkitem property.
             * 
             * @return possible object is {@link Executionworkitem }
             */
            public Executionworkitem getExecutionworkitem()
            {
                return executionworkitem;
            }
            
            /**
             * Sets the value of the executionworkitem property.
             * 
             * @param value
             *            allowed object is {@link Executionworkitem }
             */
            public void setExecutionworkitem(Executionworkitem value)
            {
                this.executionworkitem = value;
            }
            
            /**
             * Gets the value of the requirement property.
             * 
             * @return possible object is {@link Requirement }
             */
            public Requirement getRequirement()
            {
                return requirement;
            }
            
            /**
             * Sets the value of the requirement property.
             * 
             * @param value
             *            allowed object is {@link Requirement }
             */
            public void setRequirement(Requirement value)
            {
                this.requirement = value;
            }
            
            /**
             * Gets the value of the datapool property.
             * 
             * @return possible object is {@link Datapool }
             */
            public Datapool getDatapool()
            {
                return datapool;
            }
            
            /**
             * Sets the value of the datapool property.
             * 
             * @param value
             *            allowed object is {@link Datapool }
             */
            public void setDatapool(Datapool value)
            {
                this.datapool = value;
            }
            
            /**
             * Gets the value of the tooladapter property.
             * 
             * @return possible object is {@link Tooladapter }
             */
            public Tooladapter getTooladapter()
            {
                return tooladapter;
            }
            
            /**
             * Sets the value of the tooladapter property.
             * 
             * @param value
             *            allowed object is {@link Tooladapter }
             */
            public void setTooladapter(Tooladapter value)
            {
                this.tooladapter = value;
            }
            
            /**
             * Gets the value of the adaptertask property.
             * 
             * @return possible object is {@link Adaptertask }
             */
            public Adaptertask getAdaptertask()
            {
                return adaptertask;
            }
            
            /**
             * Sets the value of the adaptertask property.
             * 
             * @param value
             *            allowed object is {@link Adaptertask }
             */
            public void setAdaptertask(Adaptertask value)
            {
                this.adaptertask = value;
            }
            
            /**
             * Gets the value of the template property.
             * 
             * @return possible object is {@link Template }
             */
            public Template getTemplate()
            {
                return template;
            }
            
            /**
             * Sets the value of the template property.
             * 
             * @param value
             *            allowed object is {@link Template }
             */
            public void setTemplate(Template value)
            {
                this.template = value;
            }
            
            /**
             * Gets the value of the testsuite property.
             * 
             * @return possible object is {@link Testsuite }
             */
            public Testsuite getTestsuite()
            {
                return testsuite;
            }
            
            /**
             * Sets the value of the testsuite property.
             * 
             * @param value
             *            allowed object is {@link Testsuite }
             */
            public void setTestsuite(Testsuite value)
            {
                this.testsuite = value;
            }
            
            /**
             * Gets the value of the keyword property.
             * 
             * @return possible object is {@link Keyword }
             */
            public Keyword getKeyword()
            {
                return keyword;
            }
            
            /**
             * Sets the value of the keyword property.
             * 
             * @param value
             *            allowed object is {@link Keyword }
             */
            public void setKeyword(Keyword value)
            {
                this.keyword = value;
            }
            
            /**
             * Gets the value of the testsuitelog property.
             * 
             * @return possible object is {@link Testsuitelog }
             */
            public Testsuitelog getTestsuitelog()
            {
                return testsuitelog;
            }
            
            /**
             * Sets the value of the testsuitelog property.
             * 
             * @param value
             *            allowed object is {@link Testsuitelog }
             */
            public void setTestsuitelog(Testsuitelog value)
            {
                this.testsuitelog = value;
            }
            
            /**
             * Gets the value of the suiteexecutionrecord property.
             * 
             * @return possible object is {@link Suiteexecutionrecord }
             */
            public Suiteexecutionrecord getSuiteexecutionrecord()
            {
                return suiteexecutionrecord;
            }
            
            /**
             * Sets the value of the suiteexecutionrecord property.
             * 
             * @param value
             *            allowed object is {@link Suiteexecutionrecord }
             */
            public void setSuiteexecutionrecord(Suiteexecutionrecord value)
            {
                this.suiteexecutionrecord = value;
            }
            
            /**
             * Gets the value of the configuration property.
             * 
             * @return possible object is {@link Configuration }
             */
            public Configuration getConfiguration()
            {
                return configuration;
            }
            
            /**
             * Sets the value of the configuration property.
             * 
             * @param value
             *            allowed object is {@link Configuration }
             */
            public void setConfiguration(Configuration value)
            {
                this.configuration = value;
            }
            
            /**
             * Gets the value of the remotescript property.
             * 
             * @return possible object is {@link Remotescript }
             */
            public Remotescript getRemotescript()
            {
                return remotescript;
            }
            
            /**
             * Sets the value of the remotescript property.
             * 
             * @param value
             *            allowed object is {@link Remotescript }
             */
            public void setRemotescript(Remotescript value)
            {
                this.remotescript = value;
            }
            
            /**
             * Gets the value of the request property.
             * 
             * @return possible object is {@link Request }
             */
            public Request getRequest()
            {
                return request;
            }
            
            /**
             * Sets the value of the request property.
             * 
             * @param value
             *            allowed object is {@link Request }
             */
            public void setRequest(Request value)
            {
                this.request = value;
            }
            
            /**
             * Gets the value of the reservation property.
             * 
             * @return possible object is {@link Reservation }
             */
            public Reservation getReservation()
            {
                return reservation;
            }
            
            /**
             * Sets the value of the reservation property.
             * 
             * @param value
             *            allowed object is {@link Reservation }
             */
            public void setReservation(Reservation value)
            {
                this.reservation = value;
            }
            
            /**
             * Gets the value of the resourcecollection property.
             * 
             * @return possible object is {@link Resourcecollection }
             */
            public Resourcecollection getResourcecollection()
            {
                return resourcecollection;
            }
            
            /**
             * Sets the value of the resourcecollection property.
             * 
             * @param value
             *            allowed object is {@link Resourcecollection }
             */
            public void setResourcecollection(Resourcecollection value)
            {
                this.resourcecollection = value;
            }
            
            /**
             * Gets the value of the resourcegroup property.
             * 
             * @return possible object is {@link Resourcegroup }
             */
            public Resourcegroup getResourcegroup()
            {
                return resourcegroup;
            }
            
            /**
             * Sets the value of the resourcegroup property.
             * 
             * @param value
             *            allowed object is {@link Resourcegroup }
             */
            public void setResourcegroup(Resourcegroup value)
            {
                this.resourcegroup = value;
            }
            
            /**
             * Gets the value of the labresource property.
             * 
             * @return possible object is {@link Labresource }
             */
            public Labresource getLabresource()
            {
                return labresource;
            }
            
            /**
             * Sets the value of the labresource property.
             * 
             * @param value
             *            allowed object is {@link Labresource }
             */
            public void setLabresource(Labresource value)
            {
                this.labresource = value;
            }
            
            /**
             * Gets the value of the job property.
             * 
             * @return possible object is {@link Job }
             */
            public Job getJob()
            {
                return job;
            }
            
            /**
             * Sets the value of the job property.
             * 
             * @param value
             *            allowed object is {@link Job }
             */
            public void setJob(Job value)
            {
                this.job = value;
            }
            
            /**
             * Gets the value of the jobresult property.
             * 
             * @return possible object is {@link Jobresult }
             */
            public Jobresult getJobresult()
            {
                return jobresult;
            }
            
            /**
             * Sets the value of the jobresult property.
             * 
             * @param value
             *            allowed object is {@link Jobresult }
             */
            public void setJobresult(Jobresult value)
            {
                this.jobresult = value;
            }
            
            /**
             * Gets the value of the teamarea property.
             * 
             * @return possible object is {@link LegacyTeamArea }
             */
            public LegacyTeamArea getTeamarea()
            {
                return teamarea;
            }
            
            /**
             * Sets the value of the teamarea property.
             * 
             * @param value
             *            allowed object is {@link LegacyTeamArea }
             */
            public void setTeamarea(LegacyTeamArea value)
            {
                this.teamarea = value;
            }
            
            /**
             * Gets the value of the contributor property.
             * 
             * @return possible object is {@link Contributor }
             */
            public Contributor getContributor()
            {
                return contributor;
            }
            
            /**
             * Sets the value of the contributor property.
             * 
             * @param value
             *            allowed object is {@link Contributor }
             */
            public void setContributor(Contributor value)
            {
                this.contributor = value;
            }
            
            /**
             * Gets the value of the workitem property.
             * 
             * @return possible object is {@link Workitem }
             */
            public Workitem getWorkitem()
            {
                return workitem;
            }
            
            /**
             * Sets the value of the workitem property.
             * 
             * @param value
             *            allowed object is {@link Workitem }
             */
            public void setWorkitem(Workitem value)
            {
                this.workitem = value;
            }
            
            /**
             * Gets the value of the buildrecord property.
             * 
             * @return possible object is {@link Buildrecord }
             */
            public Buildrecord getBuildrecord()
            {
                return buildrecord;
            }
            
            /**
             * Sets the value of the buildrecord property.
             * 
             * @param value
             *            allowed object is {@link Buildrecord }
             */
            public void setBuildrecord(Buildrecord value)
            {
                this.buildrecord = value;
            }
            
            /**
             * Gets the value of the builddefinition property.
             * 
             * @return possible object is {@link Builddefinition }
             */
            public Builddefinition getBuilddefinition()
            {
                return builddefinition;
            }
            
            /**
             * Sets the value of the builddefinition property.
             * 
             * @param value
             *            allowed object is {@link Builddefinition }
             */
            public void setBuilddefinition(Builddefinition value)
            {
                this.builddefinition = value;
            }
            
            /**
             * Gets the value of the testcell property.
             * 
             * @return possible object is {@link Testcell }
             */
            public Testcell getTestcell()
            {
                return testcell;
            }
            
            /**
             * Sets the value of the testcell property.
             * 
             * @param value
             *            allowed object is {@link Testcell }
             */
            public void setTestcell(Testcell value)
            {
                this.testcell = value;
            }
            
            /**
             * Gets the value of the objective property.
             * 
             * @return possible object is {@link Objective }
             */
            public Objective getObjective()
            {
                return objective;
            }
            
            /**
             * Sets the value of the objective property.
             * 
             * @param value
             *            allowed object is {@link Objective }
             */
            public void setObjective(Objective value)
            {
                this.objective = value;
            }
            
            /**
             * Gets the value of the project property.
             * 
             * @return possible object is {@link Project }
             */
            public Project getProject()
            {
                return project;
            }
            
            /**
             * Sets the value of the project property.
             * 
             * @param value
             *            allowed object is {@link Project }
             */
            public void setProject(Project value)
            {
                this.project = value;
            }
            
            /**
             * Gets the value of the attachment property.
             * 
             * @return possible object is {@link Attachment }
             */
            public Attachment getAttachment()
            {
                return attachment;
            }
            
            /**
             * Sets the value of the attachment property.
             * 
             * @param value
             *            allowed object is {@link Attachment }
             */
            public void setAttachment(Attachment value)
            {
                this.attachment = value;
            }
            
            /**
             * Gets the value of the category property.
             * 
             * @return possible object is {@link Category }
             */
            public Category getCategory()
            {
                return category;
            }
            
            /**
             * Sets the value of the category property.
             * 
             * @param value
             *            allowed object is {@link Category }
             */
            public void setCategory(Category value)
            {
                this.category = value;
            }
            
            /**
             * Gets the value of the categoryType property.
             * 
             * @return possible object is {@link CategoryType }
             */
            public CategoryType getCategoryType()
            {
                return categoryType;
            }
            
            /**
             * Sets the value of the categoryType property.
             * 
             * @param value
             *            allowed object is {@link CategoryType }
             */
            public void setCategoryType(CategoryType value)
            {
                this.categoryType = value;
            }
            
            /**
             * Gets the value of the type property.
             * 
             * @return possible object is {@link String }
             */
            public String getType()
            {
                return type;
            }
            
            /**
             * Sets the value of the type property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setType(String value)
            {
                this.type = value;
            }
            
        }
        
        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Link
        {
            
            @XmlAttribute
            protected String href;
            
            @XmlAttribute
            protected String rel;
            
            @XmlAttribute
            protected String type;
            
            /**
             * Gets the value of the href property.
             * 
             * @return possible object is {@link String }
             */
            public String getHref()
            {
                return href;
            }
            
            /**
             * Sets the value of the href property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setHref(String value)
            {
                this.href = value;
            }
            
            /**
             * Gets the value of the rel property.
             * 
             * @return possible object is {@link String }
             */
            public String getRel()
            {
                return rel;
            }
            
            /**
             * Sets the value of the rel property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setRel(String value)
            {
                this.rel = value;
            }
            
            /**
             * Gets the value of the type property.
             * 
             * @return possible object is {@link String }
             */
            public String getType()
            {
                return type;
            }
            
            /**
             * Sets the value of the type property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setType(String value)
            {
                this.type = value;
            }
            
        }
        
        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;any processContents='skip' namespace='http://www.w3.org/1999/xhtml' maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"content"})
        public static class Summary
        {
            
            @XmlMixed
            @XmlAnyElement
            protected List<Object> content;
            
            @XmlAttribute
            protected String       type;
            
            /**
             * Gets the value of the content property.
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the content property.
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getContent().add(newItem);
             * </pre>
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String } {@link Element }
             */
            public List<Object> getContent()
            {
                if (content == null)
                {
                    content = new ArrayList<Object>();
                }
                return this.content;
            }
            
            /**
             * Gets the value of the type property.
             * 
             * @return possible object is {@link String }
             */
            public String getType()
            {
                return type;
            }
            
            /**
             * Sets the value of the type property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setType(String value)
            {
                this.type = value;
            }
            
        }
        
        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"content"})
        public static class Title
        {
            
            @XmlValue
            protected String content;
            
            @XmlAttribute
            protected String type;
            
            /**
             * Gets the value of the content property.
             * 
             * @return possible object is {@link String }
             */
            public String getContent()
            {
                return content;
            }
            
            /**
             * Sets the value of the content property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setContent(String value)
            {
                this.content = value;
            }
            
            /**
             * Gets the value of the type property.
             * 
             * @return possible object is {@link String }
             */
            public String getType()
            {
                return type;
            }
            
            /**
             * Sets the value of the type property.
             * 
             * @param value
             *            allowed object is {@link String }
             */
            public void setType(String value)
            {
                this.type = value;
            }
            
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Link
    {
        
        @XmlAttribute
        protected String href;
        
        @XmlAttribute
        protected String rel;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * Gets the value of the rel property.
         * 
         * @return possible object is {@link String }
         */
        public String getRel()
        {
            return rel;
        }
        
        /**
         * Sets the value of the rel property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setRel(String value)
        {
            this.rel = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"content"})
    public static class Title
    {
        
        @XmlValue
        protected String content;
        
        @XmlAttribute
        protected String type;
        
        /**
         * Gets the value of the content property.
         * 
         * @return possible object is {@link String }
         */
        public String getContent()
        {
            return content;
        }
        
        /**
         * Sets the value of the content property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setContent(String value)
        {
            this.content = value;
        }
        
        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link String }
         */
        public String getType()
        {
            return type;
        }
        
        /**
         * Sets the value of the type property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setType(String value)
        {
            this.type = value;
        }
        
    }
    
}
