//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.28 at 12:49:50 PM EDT 
//


package org.w3._2005.atom;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2005.atom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2005.atom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Feed.Entry }
     * 
     */
    public Feed.Entry createFeedEntry() {
        return new Feed.Entry();
    }

    /**
     * Create an instance of {@link Feed.Entry.Summary }
     * 
     */
    public Feed.Entry.Summary createFeedEntrySummary() {
        return new Feed.Entry.Summary();
    }

    /**
     * Create an instance of {@link Feed.Link }
     * 
     */
    public Feed.Link createFeedLink() {
        return new Feed.Link();
    }

    /**
     * Create an instance of {@link Feed.Entry.Content }
     * 
     */
    public Feed.Entry.Content createFeedEntryContent() {
        return new Feed.Entry.Content();
    }

    /**
     * Create an instance of {@link Feed.Title }
     * 
     */
    public Feed.Title createFeedTitle() {
        return new Feed.Title();
    }

    /**
     * Create an instance of {@link Feed.Entry.Title }
     * 
     */
    public Feed.Entry.Title createFeedEntryTitle() {
        return new Feed.Entry.Title();
    }

    /**
     * Create an instance of {@link Feed.Entry.Link }
     * 
     */
    public Feed.Entry.Link createFeedEntryLink() {
        return new Feed.Entry.Link();
    }

}
