//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.28 at 12:49:50 PM EDT
//

package com.ibm.rqm.xml.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="planningEffort" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="executionEffort" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"planningEffort", "executionEffort"})
@XmlRootElement(name = "estimation")
public class Estimation
{
    
    protected Integer planningEffort;
    
    protected Integer executionEffort;
    
    /**
     * Gets the value of the planningEffort property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getPlanningEffort()
    {
        return planningEffort;
    }
    
    /**
     * Sets the value of the planningEffort property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     */
    public void setPlanningEffort(Integer value)
    {
        this.planningEffort = value;
    }
    
    /**
     * Gets the value of the executionEffort property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getExecutionEffort()
    {
        return executionEffort;
    }
    
    /**
     * Sets the value of the executionEffort property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     */
    public void setExecutionEffort(Integer value)
    {
        this.executionEffort = value;
    }
    
}
