//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.28 at 12:49:50 PM EDT
//

package com.ibm.rqm.xml.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://jazz.net/xmlns/alm/qm/v0.1/}reportableArtifact">
 *       &lt;sequence>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.testCaseExpectedResults" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.testCasePostCondition" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.testCasePreCondition" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.caseTestDescription" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.caseTestPreparation" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.caseTestScope" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.testCaseNotes" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="com.ibm.rqm.planning.editor.section.testCaseDesign" type="{http://jazz.net/xmlns/alm/qm/v0.1/}richtext" minOccurs="0"/>
 *         &lt;element name="webId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}alias" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}creationDate"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}updated"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}state"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}creator"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/v0.1/}owner"/>
 *         &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estimate" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="trigger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="suspect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}approvals" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}risk" minOccurs="0"/>
 *         &lt;element name="category" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="termUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="valueUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}variables"/>
 *         &lt;element name="testscript" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="remotescript" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="template" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="requirement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *                 &lt;attribute name="externalReqId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="reqProId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="reqProProject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="workitem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *                 &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attachment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}customAttributes" minOccurs="0"/>
 *         &lt;element ref="{http://jazz.net/xmlns/alm/qm/v0.1/}markerAny"/>
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "webId", "alias", "title", "description", "creationDate", "updated", "state", "creator", "owner", "locked", "weight", "priority", "estimate", "trigger", "activity", "suspect", "approvals", "risk", "category", "variables", "testscript", "remotescript", "template", "requirement", "workitem", "attachment", "customAttributes", "markerAny", "any"})
@XmlRootElement(name = "testcase")
public class Testcase extends ReportableArtifact
{
    
    protected Integer                     webId;
    
    protected List<Alias>                 alias;
    
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected String                      title;
    
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected String                      description;
    
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar        creationDate;
    
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar        updated;
    
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected State                       state;
    
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected Creator                     creator;
    
    @XmlElement(namespace = "http://jazz.net/xmlns/alm/v0.1/", required = true)
    protected Owner                       owner;
    
    protected Boolean                     locked;
    
    protected Integer                     weight;
    
    protected String                      priority;
    
    protected Long                        estimate;
    
    @XmlElement(required = true)
    protected String                      trigger;
    
    @XmlElement(required = true)
    protected String                      activity;
    
    protected Boolean                     suspect;
    
    protected Approvals                   approvals;
    
    protected Risk                        risk;
    
    protected List<Testcase.Category>     category;
    
    @XmlElement(required = true)
    protected Variables                   variables;
    
    protected List<Testcase.Testscript>   testscript;
    
    protected List<Testcase.Remotescript> remotescript;
    
    protected Testcase.Template           template;
    
    protected List<Testcase.Requirement>  requirement;
    
    protected List<Testcase.Workitem>     workitem;
    
    protected List<Testcase.Attachment>   attachment;
    
    protected CustomAttributes            customAttributes;
    
    @XmlElement(required = true)
    protected String                      markerAny;
    
    @XmlAnyElement
    protected List<Element>               any;
    
    /**
     * Gets the value of the webId property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getWebId()
    {
        return webId;
    }
    
    /**
     * Sets the value of the webId property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     */
    public void setWebId(Integer value)
    {
        this.webId = value;
    }
    
    /**
     * Gets the value of the alias property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the alias property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAlias().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Alias }
     */
    public List<Alias> getAlias()
    {
        if (alias == null)
        {
            alias = new ArrayList<Alias>();
        }
        return this.alias;
    }
    
    /**
     * A name given to the test case.
     * 
     * @return possible object is {@link String }
     */
    public String getTitle()
    {
        return title;
    }
    
    /**
     * Sets the value of the title property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setTitle(String value)
    {
        this.title = value;
    }
    
    /**
     * An account of the test case.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }
    
    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }
    
    /**
     * Gets the value of the creationDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCreationDate()
    {
        return creationDate;
    }
    
    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     */
    public void setCreationDate(XMLGregorianCalendar value)
    {
        this.creationDate = value;
    }
    
    /**
     * [READ-ONLY] The last modification date of a resource. Format is XML dateTime.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getUpdated()
    {
        return updated;
    }
    
    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     */
    public void setUpdated(XMLGregorianCalendar value)
    {
        this.updated = value;
    }
    
    /**
     * An ID of the current state of the test case. Unless otherwise specified the possible values are:
     * <ul>
     * <li>com.ibm.rqm.planning.common.new</li>
     * <li>com.ibm.rqm.planning.common.underreview</li>
     * <li>com.ibm.rqm.planning.common.approved</li>
     * <li>com.ibm.rqm.planning.common.retired</li>
     * </ul>
     * 
     * @return possible object is {@link State }
     */
    public State getState()
    {
        return state;
    }
    
    /**
     * Sets the value of the state property.
     * 
     * @param value
     *            allowed object is {@link State }
     */
    public void setState(State value)
    {
        this.state = value;
    }
    
    /**
     * The contributor that created the test case.
     * 
     * @return possible object is {@link Creator }
     */
    public Creator getCreator()
    {
        return creator;
    }
    
    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *            allowed object is {@link Creator }
     */
    public void setCreator(Creator value)
    {
        this.creator = value;
    }
    
    /**
     * The contributor that owns the test case.
     * 
     * @return possible object is {@link Owner }
     */
    public Owner getOwner()
    {
        return owner;
    }
    
    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *            allowed object is {@link Owner }
     */
    public void setOwner(Owner value)
    {
        this.owner = value;
    }
    
    /**
     * Gets the value of the locked property.
     * 
     * @return possible object is {@link Boolean }
     */
    public Boolean isLocked()
    {
        return locked;
    }
    
    /**
     * Sets the value of the locked property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     */
    public void setLocked(Boolean value)
    {
        this.locked = value;
    }
    
    /**
     * Gets the value of the weight property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getWeight()
    {
        return weight;
    }
    
    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     */
    public void setWeight(Integer value)
    {
        this.weight = value;
    }
    
    /**
     * Gets the value of the priority property.
     * 
     * @return possible object is {@link String }
     */
    public String getPriority()
    {
        return priority;
    }
    
    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setPriority(String value)
    {
        this.priority = value;
    }
    
    /**
     * Gets the value of the estimate property.
     * 
     * @return possible object is {@link Long }
     */
    public Long getEstimate()
    {
        return estimate;
    }
    
    /**
     * Sets the value of the estimate property.
     * 
     * @param value
     *            allowed object is {@link Long }
     */
    public void setEstimate(Long value)
    {
        this.estimate = value;
    }
    
    /**
     * Gets the value of the trigger property.
     * 
     * @return possible object is {@link String }
     */
    public String getTrigger()
    {
        return trigger;
    }
    
    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setTrigger(String value)
    {
        this.trigger = value;
    }
    
    /**
     * Gets the value of the activity property.
     * 
     * @return possible object is {@link String }
     */
    public String getActivity()
    {
        return activity;
    }
    
    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setActivity(String value)
    {
        this.activity = value;
    }
    
    /**
     * Gets the value of the suspect property.
     * 
     * @return possible object is {@link Boolean }
     */
    public Boolean isSuspect()
    {
        return suspect;
    }
    
    /**
     * Sets the value of the suspect property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     */
    public void setSuspect(Boolean value)
    {
        this.suspect = value;
    }
    
    /**
     * An authorization granted for the test case.
     * 
     * @return possible object is {@link Approvals }
     */
    public Approvals getApprovals()
    {
        return approvals;
    }
    
    /**
     * Sets the value of the approvals property.
     * 
     * @param value
     *            allowed object is {@link Approvals }
     */
    public void setApprovals(Approvals value)
    {
        this.approvals = value;
    }
    
    /**
     * The calculated risk of the test case.
     * 
     * @return possible object is {@link Risk }
     */
    public Risk getRisk()
    {
        return risk;
    }
    
    /**
     * Sets the value of the risk property.
     * 
     * @param value
     *            allowed object is {@link Risk }
     */
    public void setRisk(Risk value)
    {
        this.risk = value;
    }
    
    /**
     * Gets the value of the category property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the category property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCategory().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Testcase.Category }
     */
    public List<Testcase.Category> getCategory()
    {
        if (category == null)
        {
            category = new ArrayList<Testcase.Category>();
        }
        return this.category;
    }
    
    /**
     * Gets the value of the variables property.
     * 
     * @return possible object is {@link Variables }
     */
    public Variables getVariables()
    {
        return variables;
    }
    
    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *            allowed object is {@link Variables }
     */
    public void setVariables(Variables value)
    {
        this.variables = value;
    }
    
    /**
     * Gets the value of the testscript property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the testscript property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTestscript().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Testcase.Testscript }
     */
    public List<Testcase.Testscript> getTestscript()
    {
        if (testscript == null)
        {
            testscript = new ArrayList<Testcase.Testscript>();
        }
        return this.testscript;
    }
    
    /**
     * Gets the value of the remotescript property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the remotescript property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRemotescript().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Testcase.Remotescript }
     */
    public List<Testcase.Remotescript> getRemotescript()
    {
        if (remotescript == null)
        {
            remotescript = new ArrayList<Testcase.Remotescript>();
        }
        return this.remotescript;
    }
    
    /**
     * Gets the value of the template property.
     * 
     * @return possible object is {@link Testcase.Template }
     */
    public Testcase.Template getTemplate()
    {
        return template;
    }
    
    /**
     * Sets the value of the template property.
     * 
     * @param value
     *            allowed object is {@link Testcase.Template }
     */
    public void setTemplate(Testcase.Template value)
    {
        this.template = value;
    }
    
    /**
     * Gets the value of the requirement property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the requirement property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRequirement().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Testcase.Requirement }
     */
    public List<Testcase.Requirement> getRequirement()
    {
        if (requirement == null)
        {
            requirement = new ArrayList<Testcase.Requirement>();
        }
        return this.requirement;
    }
    
    /**
     * Gets the value of the workitem property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the workitem property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getWorkitem().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Testcase.Workitem }
     */
    public List<Testcase.Workitem> getWorkitem()
    {
        if (workitem == null)
        {
            workitem = new ArrayList<Testcase.Workitem>();
        }
        return this.workitem;
    }
    
    /**
     * Gets the value of the attachment property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the attachment property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAttachment().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Testcase.Attachment }
     */
    public List<Testcase.Attachment> getAttachment()
    {
        if (attachment == null)
        {
            attachment = new ArrayList<Testcase.Attachment>();
        }
        return this.attachment;
    }
    
    /**
     * User defined custom attribute name/value data on this artifact.
     * 
     * @return possible object is {@link CustomAttributes }
     */
    public CustomAttributes getCustomAttributes()
    {
        return customAttributes;
    }
    
    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *            allowed object is {@link CustomAttributes }
     */
    public void setCustomAttributes(CustomAttributes value)
    {
        this.customAttributes = value;
    }
    
    /**
     * [READ-ONLY] A empty marker.
     * 
     * @return possible object is {@link String }
     */
    public String getMarkerAny()
    {
        return markerAny;
    }
    
    /**
     * Sets the value of the markerAny property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setMarkerAny(String value)
    {
        this.markerAny = value;
    }
    
    /**
     * Gets the value of the any property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the any property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAny().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Element }
     */
    public List<Element> getAny()
    {
        if (any == null)
        {
            any = new ArrayList<Element>();
        }
        return this.any;
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Attachment
    {
        
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * [DEPRECATED] [READ-ONLY]
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="termUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="valueUUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Category
    {
        
        @XmlAttribute
        protected String term;
        
        @XmlAttribute
        protected String value;
        
        @XmlAttribute
        protected String termUUID;
        
        @XmlAttribute
        protected String valueUUID;
        
        /**
         * Gets the value of the term property.
         * 
         * @return possible object is {@link String }
         */
        public String getTerm()
        {
            return term;
        }
        
        /**
         * Sets the value of the term property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setTerm(String value)
        {
            this.term = value;
        }
        
        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         */
        public String getValue()
        {
            return value;
        }
        
        /**
         * Sets the value of the value property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setValue(String value)
        {
            this.value = value;
        }
        
        /**
         * Gets the value of the termUUID property.
         * 
         * @return possible object is {@link String }
         */
        public String getTermUUID()
        {
            return termUUID;
        }
        
        /**
         * Sets the value of the termUUID property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setTermUUID(String value)
        {
            this.termUUID = value;
        }
        
        /**
         * Gets the value of the valueUUID property.
         * 
         * @return possible object is {@link String }
         */
        public String getValueUUID()
        {
            return valueUUID;
        }
        
        /**
         * Sets the value of the valueUUID property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setValueUUID(String value)
        {
            this.valueUUID = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Remotescript
    {
        
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * [DEPRECATED] [READ-ONLY]
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *       &lt;attribute name="externalReqId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="reqProId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="reqProProject" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Requirement
    {
        
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;
        
        @XmlAttribute
        protected String externalReqId;
        
        @XmlAttribute
        protected String reqProId;
        
        @XmlAttribute
        protected String reqProProject;
        
        @XmlAttribute
        protected String rel;
        
        @XmlAttribute
        protected String summary;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * [DEPRECATED] [READ-ONLY]
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
        /**
         * Gets the value of the externalReqId property.
         * 
         * @return possible object is {@link String }
         */
        public String getExternalReqId()
        {
            return externalReqId;
        }
        
        /**
         * Sets the value of the externalReqId property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setExternalReqId(String value)
        {
            this.externalReqId = value;
        }
        
        /**
         * Gets the value of the reqProId property.
         * 
         * @return possible object is {@link String }
         */
        public String getReqProId()
        {
            return reqProId;
        }
        
        /**
         * Sets the value of the reqProId property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setReqProId(String value)
        {
            this.reqProId = value;
        }
        
        /**
         * Gets the value of the reqProProject property.
         * 
         * @return possible object is {@link String }
         */
        public String getReqProProject()
        {
            return reqProProject;
        }
        
        /**
         * Sets the value of the reqProProject property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setReqProProject(String value)
        {
            this.reqProProject = value;
        }
        
        /**
         * Gets the value of the rel property.
         * 
         * @return possible object is {@link String }
         */
        public String getRel()
        {
            return rel;
        }
        
        /**
         * Sets the value of the rel property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setRel(String value)
        {
            this.rel = value;
        }
        
        /**
         * Gets the value of the summary property.
         * 
         * @return possible object is {@link String }
         */
        public String getSummary()
        {
            return summary;
        }
        
        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setSummary(String value)
        {
            this.summary = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Template
    {
        
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * [DEPRECATED] [READ-ONLY]
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testscript
    {
        
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * [DEPRECATED] [READ-ONLY]
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
    }
    
    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{http://schema.ibm.com/vega/2008/}id"/>
     *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Workitem
    {
        
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String href;
        
        @XmlAttribute(namespace = "http://schema.ibm.com/vega/2008/")
        protected String id;
        
        @XmlAttribute
        protected String rel;
        
        @XmlAttribute
        protected String summary;
        
        /**
         * Gets the value of the href property.
         * 
         * @return possible object is {@link String }
         */
        public String getHref()
        {
            return href;
        }
        
        /**
         * Sets the value of the href property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setHref(String value)
        {
            this.href = value;
        }
        
        /**
         * [DEPRECATED] [READ-ONLY]
         * 
         * @return possible object is {@link String }
         */
        public String getId()
        {
            return id;
        }
        
        /**
         * Sets the value of the id property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setId(String value)
        {
            this.id = value;
        }
        
        /**
         * Gets the value of the rel property.
         * 
         * @return possible object is {@link String }
         */
        public String getRel()
        {
            return rel;
        }
        
        /**
         * Sets the value of the rel property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setRel(String value)
        {
            this.rel = value;
        }
        
        /**
         * Gets the value of the summary property.
         * 
         * @return possible object is {@link String }
         */
        public String getSummary()
        {
            return summary;
        }
        
        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *            allowed object is {@link String }
         */
        public void setSummary(String value)
        {
            this.summary = value;
        }
        
    }
    
}
