// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions. Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.demoScripts.innovate2011.hazelcast.queuedExecution;

import com.advancedrft.common.lang.Reflection;
import com.rational.test.ft.script.RationalTestScript;

/**
 * Script Name : <b>ScriptExecutionHandler</b><br>
 * Generated : <b>2011/05/29 1:30:36 PM</b><br>
 * Description : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since May 29, 2011
 * @author vmuser
 */
public abstract class ScriptExecutionHandlerHelper extends RationalTestScript
{
    
    protected ScriptExecutionHandlerHelper()
    {
        Reflection.foreignClassLoaders.add(getClass().getClassLoader());
        setScriptName("demoScripts.innovate2011.hazelcast.queuedExecution.ScriptExecutionHandler");
    }
    
}
