//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalCache.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalCategory
    {
    	public int ID { get; set; }
    	public int TestcaseID { get; set; }
    	public string Name { get; set; }
    	public string Value { get; set; }
    
    	public virtual LocalTestcase Testcase { get; set; }
    }
}
