//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalCache.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RQMCache : DbContext
    {
        public RQMCache()
            : base("name=RQMCache")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LocalCategory> LocalCategories { get; set; }
        public DbSet<LocalProject> LocalProjects { get; set; }
        public DbSet<LocalTestcase> LocalTestcases { get; set; }
        public DbSet<LocalTestscript> LocalTestscripts { get; set; }
    }
}
